"""add lat lng to hens and animals

Revision ID: 0ab31d5c0eb2
Revises: f3cdccd6ab4c
Create Date: 2026-09-09 09:17:23.524641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab31d5c0eb2'
down_revision: Union[str, Sequence[str], None] = 'f3cdccd6ab4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))

    with op.batch_alter_table('hens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hens', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
