"""add animal wallet topups

Revision ID: 77ca06b7cd52
Revises: 0ab31d5c0eb2
Create Date: 2026-09-09 12:14:43.553025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ca06b7cd52'
down_revision: Union[str, Sequence[str], None] = '0ab31d5c0eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_wallet_topups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('amount_czk', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_reference', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal_wallet_topups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_wallet_topups_animal_id'), ['animal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_wallet_topups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_wallet_topups_animal_id'))

    op.drop_table('animal_wallet_topups')
    # ### end Alembic commands ###
