"""add fk indexes and updated_at timestamps

Revision ID: f3cdccd6ab4c
Revises: 24190d4fa3db
Create Date: 2026-09-07 09:33:12.643233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cdccd6ab4c'
down_revision: Union[str, Sequence[str], None] = '24190d4fa3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_deliveries_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('animal_paused_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_paused_days_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('animal_product_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_product_log_entries_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_animals_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_hen_id'), ['hen_id'], unique=False)

    with op.batch_alter_table('farm_animal_offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farm_animal_offerings_farm_id'), ['farm_id'], unique=False)

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('feed_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_log_entries_hen_id'), ['hen_id'], unique=False)

    with op.batch_alter_table('hens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hens_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('meat_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_meat_shares_farm_id'), ['farm_id'], unique=False)

    with op.batch_alter_table('paused_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paused_days_hen_id'), ['hen_id'], unique=False)

    with op.batch_alter_table('share_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_contributions_meat_share_id'), ['meat_share_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_contributions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('wallet_topups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_topups_hen_id'), ['hen_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_topups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_topups_hen_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('share_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_contributions_user_id'))
        batch_op.drop_index(batch_op.f('ix_share_contributions_meat_share_id'))

    with op.batch_alter_table('paused_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paused_days_hen_id'))

    with op.batch_alter_table('meat_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meat_shares_farm_id'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('hens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hens_user_id'))
        batch_op.drop_index(batch_op.f('ix_hens_farm_id'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('feed_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_log_entries_hen_id'))

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('farm_animal_offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_animal_offerings_farm_id'))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_hen_id'))

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animals_user_id'))
        batch_op.drop_index(batch_op.f('ix_animals_farm_id'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('animal_product_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_product_log_entries_animal_id'))

    with op.batch_alter_table('animal_paused_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_paused_days_animal_id'))

    with op.batch_alter_table('animal_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_deliveries_animal_id'))

    # ### end Alembic commands ###
